/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "metrics.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MetricsData, MetricsData, AUTO)


PB_BIND(ResourceMetrics, ResourceMetrics, AUTO)


PB_BIND(ScopeMetrics, ScopeMetrics, AUTO)


PB_BIND(Metric, Metric, AUTO)


PB_BIND(Gauge, Gauge, AUTO)


PB_BIND(Sum, Sum, AUTO)


PB_BIND(Histogram, Histogram, AUTO)


PB_BIND(ExponentialHistogram, ExponentialHistogram, AUTO)


PB_BIND(Summary, Summary, AUTO)


PB_BIND(NumberDataPoint, NumberDataPoint, AUTO)


PB_BIND(HistogramDataPoint, HistogramDataPoint, AUTO)


PB_BIND(ExponentialHistogramDataPoint, ExponentialHistogramDataPoint, AUTO)


PB_BIND(ExponentialHistogramDataPoint_Buckets, ExponentialHistogramDataPoint_Buckets, AUTO)


PB_BIND(SummaryDataPoint, SummaryDataPoint, AUTO)


PB_BIND(SummaryDataPoint_ValueAtQuantile, SummaryDataPoint_ValueAtQuantile, AUTO)


PB_BIND(Exemplar, Exemplar, AUTO)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

